### ISSUE TITLE
Sponsor and Partners should link to respective entity's website

### ISSUE THREAD

**Issue by xprilion** [gdgcloudkol/ccd2022#24]
The logos in sponsors and partners (DSCs listed for now) should link to their websites/blogs/pages. Please add appropriate links for them that open in new tabs.

**Comment by madihamallick** [comment]
Okay 

> The logos in sponsors and partners (DSCs listed for now) should link to their websites/blogs/pages. Please add appropriate links for them that open in new tabs.

**Comment by madihamallick** [comment]
Pushed the changes so closing this @xprilion
