### ISSUE TITLE
UI update of the speaker's card

### ISSUE THREAD

**Issue by anuragsingh228** [gdgcloudkol/ccd2022#31]
Issues with current card:
- The image to give a 4-color border, shifts when the screen width is reduced.
- The size of the card is a little big.
- The texts are very bold.

Inspiration Links:
- [https://devfestindia.com/speakers](Devfest speakers list)
- We can take inspirations from these type of cards
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/33912858/181615606-a56e38ac-37b9-4736-a870-41b984e364c1.png">
- 
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/33912858/181616868-b1306b0e-27ea-44dc-a406-a3911487d747.png">

**Comment by xprilion** [comment]
Fixed in #34
